language: python
python: 3.9

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6
      - python3.7
      - python3.8
      - pypy

install:
  - pip install tox

script:
  - tox
